[project]
name = "dockertempl"
version = "0.1.0"
description = "template out dockerfiles"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.4",
    "pyyaml>=6.0.2",
    "ruff>=0.8.3",
]
